#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Simon Dick
#
# Local-only regression test: boots devtest, failtest, and the Say
# acceptance test under Copperline with a real Kickstart + a real
# AHI-installed Workbench volume, all from nondist/ (see nondist/README.md)
# -- content this repo cannot ship, so this script (unlike run_smoke.sh)
# never runs in CI. It's the fuller counterpart to copperline-smoke: that
# job proves the cross-compiled binary + bsdsocket.library path works with
# no licensed content at all; this script additionally exercises
# narrator.device/translator.library/AHI/Say, which copperline-smoke
# deliberately skips.
#
# Requires:
#   - `copperline` on PATH
#   - nondist/Kickstarts/*.rom and nondist/HardDrives/narrator (copy them
#     in per nondist/README.md -- narrator.wyoming's own dev machine's
#     copies live at ~/Documents/Amiberry/{Kickstarts,HardDrives/narrator})
#   - build/amiga/{devtest,failtest,narrator.device,translator.library}
#     already built (`make docker`)
#   - nothing else network-wise: this script writes its own temporary
#     ENV:narrator.wyoming pointing at tests/mock_wyoming_server.py (see
#     MOCK_PORT below) rather than trusting whatever's in the developer's
#     own gitignored config/narrator.wyoming
#
# Mechanism: narrator.wyoming's own tracked `boot` script is the single
# source of truth for the Say acceptance test and is never modified here.
# Instead this script temporarily swaps nondist/HardDrives/narrator's own
# S/User-Startup (never committed -- see nondist/README.md, so freely
# editable) for one that installs the device/library/prefs, runs
# devtest + failtest first, then `Execute Narrator:boot` for Say -- and
# restores the original User-Startup on exit regardless of outcome.
#
# Usage: tests/run_nondist.sh (run from the repo root)
#
# Audio capture uses Copperline 0.17+ per-source stems (--audio-stems)
# rather than the old mixed --audio-wav: build/stems/ gets master.wav plus
# one WAV per active source (paula.wav, drivesounds.wav, toccata.wav, ...),
# and the speech check runs against the stem the device is expected to
# play through -- so a floppy click in the mix can't mask silent speech.
# Stems are kept after the run for listening/comparison.
#
#   AUDIO_SOURCE=paula (default)  check speech in the Paula stem
#   AUDIO_SOURCE=toccata          enable Copperline's Toccata board and
#                                 check speech in the Toccata stem instead.
#                                 Needs the nondist Workbench set up for it:
#                                 toccata.audio in Devs:AHI + an AudioModes
#                                 entry, and the AHI unit given via AHI_UNIT
#                                 configured to a Toccata mode.
#   AHI_UNIT=N                    add `ahi_unit N` to the generated prefs
#                                 (unset = device default, unit 0)
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

MOCK_PORT=48216
BENCH_SECS=${BENCH_SECS:-180}   # generous: real Workbench boot + devtest's
                                 # own several CMD_WRITEs each pace to real
                                 # AHI playback time, not just network RTT.
AUDIO_MIN_DURATION=2.0
AUDIO_SOURCE=${AUDIO_SOURCE:-paula}
AHI_UNIT=${AHI_UNIT:-}
STEMS_DIR="$ROOT/build/stems"

case "$AUDIO_SOURCE" in
    paula|toccata) ;;
    *) echo "run_nondist.sh: AUDIO_SOURCE must be paula or toccata" >&2; exit 1 ;;
esac

ROM=$(ls nondist/Kickstarts/*.rom 2>/dev/null | head -1 || true)
HDDIR="nondist/HardDrives/narrator"
USER_STARTUP="$HDDIR/S/User-Startup"

if ! command -v copperline >/dev/null 2>&1; then
    echo "run_nondist.sh: 'copperline' not found on PATH" >&2
    exit 1
fi
if [ -z "$ROM" ]; then
    echo "run_nondist.sh: no *.rom under nondist/Kickstarts/ -- see nondist/README.md" >&2
    exit 1
fi
if [ ! -f "$HDDIR/Devs/ahi.device" ]; then
    echo "run_nondist.sh: $HDDIR missing (or has no AHI) -- see nondist/README.md" >&2
    exit 1
fi
for bin in devtest failtest narrator.device translator.library; do
    if [ ! -f "build/amiga/$bin" ]; then
        echo "run_nondist.sh: build/amiga/$bin not found -- build it first (make docker)" >&2
        exit 1
    fi
done
if [ ! -f "$USER_STARTUP" ]; then
    echo "run_nondist.sh: $USER_STARTUP not found -- unexpected nondist/ layout" >&2
    exit 1
fi

WORK=$(mktemp -d)
TOML="$WORK/machine.toml"
cat >"$TOML" <<EOF
# Generated by run_nondist.sh -- self-contained, doesn't depend on the
# developer's own config/copperline-narrator.toml.
rom = "$ROOT/$ROM"

[machine]
profile = "A1200"

[cpu]
model = "68030"
clock_mhz = 40.0

[memory]
z3 = "16M"

[[filesys]]
path = "$ROOT/$HDDIR"
volume = "Workbench"
bootpri = 6

[[filesys]]
path = "$ROOT"
volume = "Narrator"

[hostsocket]
net = "host"
EOF

if [ "$AUDIO_SOURCE" = "toccata" ]; then
    cat >>"$TOML" <<EOF

[toccata]
enabled = true
EOF
fi

# A temp prefs file has to live under one of the two mounted [[filesys]]
# volumes to be reachable from the guest at all -- $WORK (mktemp -d, under
# /tmp) isn't mounted, so this goes at the repo root instead (gitignored).
PREFS_FILE="$ROOT/.run_nondist.prefs.tmp"

cleanup() {
    [ -f "$WORK/User-Startup.orig" ] && cp "$WORK/User-Startup.orig" "$USER_STARTUP"
    rm -f devtest.log failtest.log "$PREFS_FILE"
    rm -rf "$WORK"
    [ -n "${srv_pid:-}" ] && kill "$srv_pid" 2>/dev/null || true
}
trap cleanup EXIT

cat >"$PREFS_FILE" <<EOF
host 127.0.0.1
port $MOCK_PORT
runs 1
text Regression test utterance.
EOF
[ -n "$AHI_UNIT" ] && echo "ahi_unit $AHI_UNIT" >>"$PREFS_FILE"

cp "$USER_STARTUP" "$WORK/User-Startup.orig"
# Doesn't `Execute Narrator:boot` for the Say portion -- boot's own first
# line re-copies config/narrator.wyoming over ENV:narrator.wyoming, which
# would clobber the mock-server prefs just installed below and point Say
# at whatever's in the developer's own local dev config instead. Runs the
# same Say acceptance line directly so the whole boot stays pointed at the
# mock server throughout.
cat >"$USER_STARTUP" <<'EOF'
; Temporary -- written by run_nondist.sh, restored on exit.
CD Narrator:
Stack 131072
Copy >NIL: .run_nondist.prefs.tmp ENV:narrator.wyoming
Copy >NIL: build/amiga/narrator.device   DEVS:narrator.device
Copy >NIL: build/amiga/translator.library LIBS:translator.library
build/amiga/devtest  >Narrator:devtest.log
build/amiga/failtest >Narrator:failtest.log
Copy >NIL: .run_nondist.prefs.tmp ENV:narrator.wyoming
SYS:Utilities/Say "Hello world. This is the Amiga, speaking with a neural voice over Wyoming and A.H.I."
EOF

python3 tests/mock_wyoming_server.py "$MOCK_PORT" tests/golden/fixture.pcm \
    22050 2 1 0 >/tmp/run-nondist-srv.log 2>&1 &
srv_pid=$!

mkdir -p "$STEMS_DIR"
rm -f "$STEMS_DIR"/*.wav

echo "booting under Copperline (benchmark-until ${BENCH_SECS}s emulated," \
     "checking the $AUDIO_SOURCE stem)..."
timeout 400 copperline --config "$TOML" \
    --audio-stems "$STEMS_DIR" --audio-stems-mode master,source \
    --benchmark-until "$BENCH_SECS"

kill "$srv_pid" 2>/dev/null || true
wait "$srv_pid" 2>/dev/null || true
srv_pid=

fail=0

for name in devtest failtest; do
    log="$name.log"
    echo "--- $log ---"
    if [ -f "$log" ]; then
        cat "$log"
        if ! grep -q "^PASS: $name\$" "$log"; then
            echo "FAIL: $name did not report an overall PASS"
            fail=1
        fi
    else
        echo "FAIL: $log was never written"
        fail=1
    fi
    echo "-------------"
done

# The speech check runs against the per-source stem, not the master mix:
# master.wav also carries drive sounds etc., which could mask a silent
# device. Stems for the other active sources are left in $STEMS_DIR for
# listening/A-B comparison (e.g. paula vs toccata aliasing).
STEM="$STEMS_DIR/$AUDIO_SOURCE.wav"
if [ -f "$STEM" ]; then
    python3 tests/check_audio_wav.py "$STEM" "$AUDIO_MIN_DURATION" || fail=1
else
    echo "FAIL: no $AUDIO_SOURCE stem was written (see $STEMS_DIR)"
    fail=1
fi
echo "stems kept in $STEMS_DIR:"
ls -l "$STEMS_DIR" 2>/dev/null || true

if [ "$fail" -eq 0 ]; then
    echo "PASS: run_nondist (devtest + failtest + Say, real AHI audio confirmed via $AUDIO_SOURCE stem)"
else
    echo "FAIL: run_nondist"
fi
exit $fail
